### ISSUE TITLE
TranslationManager issue repo 404

### ISSUE THREAD

**Issue by RaederDev** [humhub/translation-manager-issues#1]
We pay for Professional Edition and want to use the TranslationManager: https://marketplace.humhub.com/module/translation-manager/description plugin. Unfortunately this is broken on our PHP version. However I cannot report an issue because when you click on the website linked in the app-store: "https://github.com/humhub/translation-manager-issues" you get a 404. Where can I create issue reports for this plugin?

Specifically line 63 of TranslationSearch needs to be changed to this:
```php
 if (($original !== null && mb_stripos($original, $this->key) !== false) || ($translated !== null && mb_stripos($translated, $this->key) !== false)) {
```
as passing null to $haystack of mb_stripos is deprecated in php 8.1 and breaks on our dev environments

**Comment by yurabakhtin** [comment]
@RaederDev Thank you for the report!
@luke- Fixed in PR https://github.com/humhub/translation-manager/pull/1.

**Comment by luke-** [comment]
@yurabakhtin Thanks!

Just released v.1.1.2 which should fixes the issue.
